/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn.impl;

import org.eclipse.emf.ecore.EClass;

import sar.drone.drn.BACKWARD;
import sar.drone.drn.DrnPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>BACKWARD</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BACKWARDImpl extends DepY_ImplImpl implements BACKWARD
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BACKWARDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DrnPackage.Literals.BACKWARD;
  }

} //BACKWARDImpl
