/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import sar.drone.drn.CARREYZ;
import sar.drone.drn.DrnPackage;
import sar.drone.drn.Parametre;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>CARREYZ</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link sar.drone.drn.impl.CARREYZImpl#getCoteCST <em>Cote CST</em>}</li>
 *   <li>{@link sar.drone.drn.impl.CARREYZImpl#getCoteVAR <em>Cote VAR</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CARREYZImpl extends DepYZ_IMPLImpl implements CARREYZ
{
  /**
   * The default value of the '{@link #getCoteCST() <em>Cote CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoteCST()
   * @generated
   * @ordered
   */
  protected static final String COTE_CST_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCoteCST() <em>Cote CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoteCST()
   * @generated
   * @ordered
   */
  protected String coteCST = COTE_CST_EDEFAULT;

  /**
   * The cached value of the '{@link #getCoteVAR() <em>Cote VAR</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoteVAR()
   * @generated
   * @ordered
   */
  protected Parametre coteVAR;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CARREYZImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DrnPackage.Literals.CARREYZ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCoteCST()
  {
    return coteCST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCoteCST(String newCoteCST)
  {
    String oldCoteCST = coteCST;
    coteCST = newCoteCST;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DrnPackage.CARREYZ__COTE_CST, oldCoteCST, coteCST));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parametre getCoteVAR()
  {
    if (coteVAR != null && coteVAR.eIsProxy())
    {
      InternalEObject oldCoteVAR = (InternalEObject)coteVAR;
      coteVAR = (Parametre)eResolveProxy(oldCoteVAR);
      if (coteVAR != oldCoteVAR)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DrnPackage.CARREYZ__COTE_VAR, oldCoteVAR, coteVAR));
      }
    }
    return coteVAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parametre basicGetCoteVAR()
  {
    return coteVAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCoteVAR(Parametre newCoteVAR)
  {
    Parametre oldCoteVAR = coteVAR;
    coteVAR = newCoteVAR;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DrnPackage.CARREYZ__COTE_VAR, oldCoteVAR, coteVAR));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DrnPackage.CARREYZ__COTE_CST:
        return getCoteCST();
      case DrnPackage.CARREYZ__COTE_VAR:
        if (resolve) return getCoteVAR();
        return basicGetCoteVAR();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DrnPackage.CARREYZ__COTE_CST:
        setCoteCST((String)newValue);
        return;
      case DrnPackage.CARREYZ__COTE_VAR:
        setCoteVAR((Parametre)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DrnPackage.CARREYZ__COTE_CST:
        setCoteCST(COTE_CST_EDEFAULT);
        return;
      case DrnPackage.CARREYZ__COTE_VAR:
        setCoteVAR((Parametre)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DrnPackage.CARREYZ__COTE_CST:
        return COTE_CST_EDEFAULT == null ? coteCST != null : !COTE_CST_EDEFAULT.equals(coteCST);
      case DrnPackage.CARREYZ__COTE_VAR:
        return coteVAR != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (coteCST: ");
    result.append(coteCST);
    result.append(')');
    return result.toString();
  }

} //CARREYZImpl
