/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn.impl;

import org.eclipse.emf.ecore.EClass;

import sar.drone.drn.DrnPackage;
import sar.drone.drn.FORWARD;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>FORWARD</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FORWARDImpl extends DepY_ImplImpl implements FORWARD
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FORWARDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DrnPackage.Literals.FORWARD;
  }

} //FORWARDImpl
