/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import sar.drone.drn.Attribut;
import sar.drone.drn.ColorLed;
import sar.drone.drn.DrnPackage;
import sar.drone.drn.LedBlink;
import sar.drone.drn.Parametre;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Led Blink</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link sar.drone.drn.impl.LedBlinkImpl#getName <em>Name</em>}</li>
 *   <li>{@link sar.drone.drn.impl.LedBlinkImpl#getColor <em>Color</em>}</li>
 *   <li>{@link sar.drone.drn.impl.LedBlinkImpl#getBlink_per_secCST <em>Blink per sec CST</em>}</li>
 *   <li>{@link sar.drone.drn.impl.LedBlinkImpl#getBlink_per_secVAR <em>Blink per sec VAR</em>}</li>
 *   <li>{@link sar.drone.drn.impl.LedBlinkImpl#getAttributs <em>Attributs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LedBlinkImpl extends OptionImpl implements LedBlink
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected static final ColorLed COLOR_EDEFAULT = ColorLed.BLUE;

  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected ColorLed color = COLOR_EDEFAULT;

  /**
   * The default value of the '{@link #getBlink_per_secCST() <em>Blink per sec CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlink_per_secCST()
   * @generated
   * @ordered
   */
  protected static final String BLINK_PER_SEC_CST_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBlink_per_secCST() <em>Blink per sec CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlink_per_secCST()
   * @generated
   * @ordered
   */
  protected String blink_per_secCST = BLINK_PER_SEC_CST_EDEFAULT;

  /**
   * The cached value of the '{@link #getBlink_per_secVAR() <em>Blink per sec VAR</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlink_per_secVAR()
   * @generated
   * @ordered
   */
  protected Parametre blink_per_secVAR;

  /**
   * The cached value of the '{@link #getAttributs() <em>Attributs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributs()
   * @generated
   * @ordered
   */
  protected EList<Attribut> attributs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LedBlinkImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DrnPackage.Literals.LED_BLINK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DrnPackage.LED_BLINK__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ColorLed getColor()
  {
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setColor(ColorLed newColor)
  {
    ColorLed oldColor = color;
    color = newColor == null ? COLOR_EDEFAULT : newColor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DrnPackage.LED_BLINK__COLOR, oldColor, color));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBlink_per_secCST()
  {
    return blink_per_secCST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBlink_per_secCST(String newBlink_per_secCST)
  {
    String oldBlink_per_secCST = blink_per_secCST;
    blink_per_secCST = newBlink_per_secCST;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DrnPackage.LED_BLINK__BLINK_PER_SEC_CST, oldBlink_per_secCST, blink_per_secCST));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parametre getBlink_per_secVAR()
  {
    if (blink_per_secVAR != null && blink_per_secVAR.eIsProxy())
    {
      InternalEObject oldBlink_per_secVAR = (InternalEObject)blink_per_secVAR;
      blink_per_secVAR = (Parametre)eResolveProxy(oldBlink_per_secVAR);
      if (blink_per_secVAR != oldBlink_per_secVAR)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DrnPackage.LED_BLINK__BLINK_PER_SEC_VAR, oldBlink_per_secVAR, blink_per_secVAR));
      }
    }
    return blink_per_secVAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parametre basicGetBlink_per_secVAR()
  {
    return blink_per_secVAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBlink_per_secVAR(Parametre newBlink_per_secVAR)
  {
    Parametre oldBlink_per_secVAR = blink_per_secVAR;
    blink_per_secVAR = newBlink_per_secVAR;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DrnPackage.LED_BLINK__BLINK_PER_SEC_VAR, oldBlink_per_secVAR, blink_per_secVAR));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Attribut> getAttributs()
  {
    if (attributs == null)
    {
      attributs = new EObjectContainmentEList<Attribut>(Attribut.class, this, DrnPackage.LED_BLINK__ATTRIBUTS);
    }
    return attributs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DrnPackage.LED_BLINK__ATTRIBUTS:
        return ((InternalEList<?>)getAttributs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DrnPackage.LED_BLINK__NAME:
        return getName();
      case DrnPackage.LED_BLINK__COLOR:
        return getColor();
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_CST:
        return getBlink_per_secCST();
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_VAR:
        if (resolve) return getBlink_per_secVAR();
        return basicGetBlink_per_secVAR();
      case DrnPackage.LED_BLINK__ATTRIBUTS:
        return getAttributs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DrnPackage.LED_BLINK__NAME:
        setName((String)newValue);
        return;
      case DrnPackage.LED_BLINK__COLOR:
        setColor((ColorLed)newValue);
        return;
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_CST:
        setBlink_per_secCST((String)newValue);
        return;
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_VAR:
        setBlink_per_secVAR((Parametre)newValue);
        return;
      case DrnPackage.LED_BLINK__ATTRIBUTS:
        getAttributs().clear();
        getAttributs().addAll((Collection<? extends Attribut>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DrnPackage.LED_BLINK__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DrnPackage.LED_BLINK__COLOR:
        setColor(COLOR_EDEFAULT);
        return;
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_CST:
        setBlink_per_secCST(BLINK_PER_SEC_CST_EDEFAULT);
        return;
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_VAR:
        setBlink_per_secVAR((Parametre)null);
        return;
      case DrnPackage.LED_BLINK__ATTRIBUTS:
        getAttributs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DrnPackage.LED_BLINK__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DrnPackage.LED_BLINK__COLOR:
        return color != COLOR_EDEFAULT;
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_CST:
        return BLINK_PER_SEC_CST_EDEFAULT == null ? blink_per_secCST != null : !BLINK_PER_SEC_CST_EDEFAULT.equals(blink_per_secCST);
      case DrnPackage.LED_BLINK__BLINK_PER_SEC_VAR:
        return blink_per_secVAR != null;
      case DrnPackage.LED_BLINK__ATTRIBUTS:
        return attributs != null && !attributs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", color: ");
    result.append(color);
    result.append(", blink_per_secCST: ");
    result.append(blink_per_secCST);
    result.append(')');
    return result.toString();
  }

} //LedBlinkImpl
