/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn.impl;

import org.eclipse.emf.ecore.EClass;

import sar.drone.drn.DrnPackage;
import sar.drone.drn.MaxHeight;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Max Height</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MaxHeightImpl extends SurfaceImpl implements MaxHeight
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MaxHeightImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DrnPackage.Literals.MAX_HEIGHT;
  }

} //MaxHeightImpl
