/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BACKWARD</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sar.drone.drn.DrnPackage#getBACKWARD()
 * @model
 * @generated
 */
public interface BACKWARD extends DepY_Impl
{
} // BACKWARD
