/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bluetooth</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sar.drone.drn.DrnPackage#getBluetooth()
 * @model
 * @generated
 */
public interface Bluetooth extends ConnectionType
{
} // Bluetooth
