/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dep XZ</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sar.drone.drn.DepXZ#getName <em>Name</em>}</li>
 *   <li>{@link sar.drone.drn.DepXZ#getDistanceCST <em>Distance CST</em>}</li>
 *   <li>{@link sar.drone.drn.DepXZ#getDistanceVar <em>Distance Var</em>}</li>
 *   <li>{@link sar.drone.drn.DepXZ#getTempsCST <em>Temps CST</em>}</li>
 *   <li>{@link sar.drone.drn.DepXZ#getTempsVAR <em>Temps VAR</em>}</li>
 * </ul>
 *
 * @see sar.drone.drn.DrnPackage#getDepXZ()
 * @model
 * @generated
 */
public interface DepXZ extends DepXZ_IMPL
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see sar.drone.drn.DrnPackage#getDepXZ_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepXZ#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Distance CST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distance CST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance CST</em>' attribute.
   * @see #setDistanceCST(String)
   * @see sar.drone.drn.DrnPackage#getDepXZ_DistanceCST()
   * @model
   * @generated
   */
  String getDistanceCST();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepXZ#getDistanceCST <em>Distance CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance CST</em>' attribute.
   * @see #getDistanceCST()
   * @generated
   */
  void setDistanceCST(String value);

  /**
   * Returns the value of the '<em><b>Distance Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distance Var</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance Var</em>' reference.
   * @see #setDistanceVar(Parametre)
   * @see sar.drone.drn.DrnPackage#getDepXZ_DistanceVar()
   * @model
   * @generated
   */
  Parametre getDistanceVar();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepXZ#getDistanceVar <em>Distance Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance Var</em>' reference.
   * @see #getDistanceVar()
   * @generated
   */
  void setDistanceVar(Parametre value);

  /**
   * Returns the value of the '<em><b>Temps CST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temps CST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps CST</em>' attribute.
   * @see #setTempsCST(String)
   * @see sar.drone.drn.DrnPackage#getDepXZ_TempsCST()
   * @model
   * @generated
   */
  String getTempsCST();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepXZ#getTempsCST <em>Temps CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temps CST</em>' attribute.
   * @see #getTempsCST()
   * @generated
   */
  void setTempsCST(String value);

  /**
   * Returns the value of the '<em><b>Temps VAR</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temps VAR</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps VAR</em>' reference.
   * @see #setTempsVAR(Parametre)
   * @see sar.drone.drn.DrnPackage#getDepXZ_TempsVAR()
   * @model
   * @generated
   */
  Parametre getTempsVAR();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepXZ#getTempsVAR <em>Temps VAR</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temps VAR</em>' reference.
   * @see #getTempsVAR()
   * @generated
   */
  void setTempsVAR(Parametre value);

} // DepXZ
