/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dep XYZ IMPL</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sar.drone.drn.DrnPackage#getDepXYZ_IMPL()
 * @model
 * @generated
 */
public interface DepXYZ_IMPL extends Movement
{
} // DepXYZ_IMPL
