/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dep ZImpl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sar.drone.drn.DepZ_Impl#getName <em>Name</em>}</li>
 *   <li>{@link sar.drone.drn.DepZ_Impl#getDistanceCST <em>Distance CST</em>}</li>
 *   <li>{@link sar.drone.drn.DepZ_Impl#getTempsCST <em>Temps CST</em>}</li>
 * </ul>
 *
 * @see sar.drone.drn.DrnPackage#getDepZ_Impl()
 * @model
 * @generated
 */
public interface DepZ_Impl extends Movement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see sar.drone.drn.DrnPackage#getDepZ_Impl_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepZ_Impl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Distance CST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distance CST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance CST</em>' attribute.
   * @see #setDistanceCST(int)
   * @see sar.drone.drn.DrnPackage#getDepZ_Impl_DistanceCST()
   * @model
   * @generated
   */
  int getDistanceCST();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepZ_Impl#getDistanceCST <em>Distance CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance CST</em>' attribute.
   * @see #getDistanceCST()
   * @generated
   */
  void setDistanceCST(int value);

  /**
   * Returns the value of the '<em><b>Temps CST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temps CST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps CST</em>' attribute.
   * @see #setTempsCST(int)
   * @see sar.drone.drn.DrnPackage#getDepZ_Impl_TempsCST()
   * @model
   * @generated
   */
  int getTempsCST();

  /**
   * Sets the value of the '{@link sar.drone.drn.DepZ_Impl#getTempsCST <em>Temps CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temps CST</em>' attribute.
   * @see #getTempsCST()
   * @generated
   */
  void setTempsCST(int value);

} // DepZ_Impl
