/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see sar.drone.drn.DrnPackage
 * @generated
 */
public interface DrnFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DrnFactory eINSTANCE = sar.drone.drn.impl.DrnFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Context</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Context</em>'.
   * @generated
   */
  Context createContext();

  /**
   * Returns a new object of class '<em>Limit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Limit</em>'.
   * @generated
   */
  Limit createLimit();

  /**
   * Returns a new object of class '<em>Surface</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Surface</em>'.
   * @generated
   */
  Surface createSurface();

  /**
   * Returns a new object of class '<em>Initial Position</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Position</em>'.
   * @generated
   */
  InitialPosition createInitialPosition();

  /**
   * Returns a new object of class '<em>Initial Direction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Direction</em>'.
   * @generated
   */
  InitialDirection createInitialDirection();

  /**
   * Returns a new object of class '<em>Initial Position X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Position X</em>'.
   * @generated
   */
  InitialPositionX createInitialPositionX();

  /**
   * Returns a new object of class '<em>Initial Position Y</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Position Y</em>'.
   * @generated
   */
  InitialPositionY createInitialPositionY();

  /**
   * Returns a new object of class '<em>Max Length</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Max Length</em>'.
   * @generated
   */
  MaxLength createMaxLength();

  /**
   * Returns a new object of class '<em>Max Width</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Max Width</em>'.
   * @generated
   */
  MaxWidth createMaxWidth();

  /**
   * Returns a new object of class '<em>Max Speed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Max Speed</em>'.
   * @generated
   */
  MaxSpeed createMaxSpeed();

  /**
   * Returns a new object of class '<em>Max Heigth</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Max Heigth</em>'.
   * @generated
   */
  MaxHeigth createMaxHeigth();

  /**
   * Returns a new object of class '<em>Assignement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignement</em>'.
   * @generated
   */
  Assignement createAssignement();

  /**
   * Returns a new object of class '<em>Parametre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parametre</em>'.
   * @generated
   */
  Parametre createParametre();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Movement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Movement</em>'.
   * @generated
   */
  Movement createMovement();

  /**
   * Returns a new object of class '<em>Ref Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ref Part</em>'.
   * @generated
   */
  RefPart createRefPart();

  /**
   * Returns a new object of class '<em>And</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And</em>'.
   * @generated
   */
  And createAnd();

  /**
   * Returns a new object of class '<em>Dep YImpl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep YImpl</em>'.
   * @generated
   */
  DepY_Impl createDepY_Impl();

  /**
   * Returns a new object of class '<em>FORWARD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FORWARD</em>'.
   * @generated
   */
  FORWARD createFORWARD();

  /**
   * Returns a new object of class '<em>BACKWARD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BACKWARD</em>'.
   * @generated
   */
  BACKWARD createBACKWARD();

  /**
   * Returns a new object of class '<em>Dep XImpl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep XImpl</em>'.
   * @generated
   */
  DepX_Impl createDepX_Impl();

  /**
   * Returns a new object of class '<em>LEFT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LEFT</em>'.
   * @generated
   */
  LEFT createLEFT();

  /**
   * Returns a new object of class '<em>RIGHT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RIGHT</em>'.
   * @generated
   */
  RIGHT createRIGHT();

  /**
   * Returns a new object of class '<em>Dep ZImpl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep ZImpl</em>'.
   * @generated
   */
  DepZ_Impl createDepZ_Impl();

  /**
   * Returns a new object of class '<em>UP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UP</em>'.
   * @generated
   */
  UP createUP();

  /**
   * Returns a new object of class '<em>DOWN</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DOWN</em>'.
   * @generated
   */
  DOWN createDOWN();

  /**
   * Returns a new object of class '<em>Dep XY IMPL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep XY IMPL</em>'.
   * @generated
   */
  DepXY_IMPL createDepXY_IMPL();

  /**
   * Returns a new object of class '<em>Dep XY</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep XY</em>'.
   * @generated
   */
  DepXY createDepXY();

  /**
   * Returns a new object of class '<em>CERCLEXY</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CERCLEXY</em>'.
   * @generated
   */
  CERCLEXY createCERCLEXY();

  /**
   * Returns a new object of class '<em>CARREXY</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CARREXY</em>'.
   * @generated
   */
  CARREXY createCARREXY();

  /**
   * Returns a new object of class '<em>Dep YZ IMPL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep YZ IMPL</em>'.
   * @generated
   */
  DepYZ_IMPL createDepYZ_IMPL();

  /**
   * Returns a new object of class '<em>Dep YZ</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep YZ</em>'.
   * @generated
   */
  DepYZ createDepYZ();

  /**
   * Returns a new object of class '<em>CERCLEYZ</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CERCLEYZ</em>'.
   * @generated
   */
  CERCLEYZ createCERCLEYZ();

  /**
   * Returns a new object of class '<em>CARREYZ</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CARREYZ</em>'.
   * @generated
   */
  CARREYZ createCARREYZ();

  /**
   * Returns a new object of class '<em>Dep XZ IMPL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep XZ IMPL</em>'.
   * @generated
   */
  DepXZ_IMPL createDepXZ_IMPL();

  /**
   * Returns a new object of class '<em>Dep XZ</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep XZ</em>'.
   * @generated
   */
  DepXZ createDepXZ();

  /**
   * Returns a new object of class '<em>Dep XYZ IMPL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep XYZ IMPL</em>'.
   * @generated
   */
  DepXYZ_IMPL createDepXYZ_IMPL();

  /**
   * Returns a new object of class '<em>Dep XYZ</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep XYZ</em>'.
   * @generated
   */
  DepXYZ createDepXYZ();

  /**
   * Returns a new object of class '<em>Flip</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flip</em>'.
   * @generated
   */
  Flip createFlip();

  /**
   * Returns a new object of class '<em>Rotate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotate</em>'.
   * @generated
   */
  Rotate createRotate();

  /**
   * Returns a new object of class '<em>Wait</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wait</em>'.
   * @generated
   */
  Wait createWait();

  /**
   * Returns a new object of class '<em>Take Off</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Take Off</em>'.
   * @generated
   */
  TakeOff createTakeOff();

  /**
   * Returns a new object of class '<em>Land</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Land</em>'.
   * @generated
   */
  Land createLand();

  /**
   * Returns a new object of class '<em>Device</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Device</em>'.
   * @generated
   */
  Device createDevice();

  /**
   * Returns a new object of class '<em>Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaration</em>'.
   * @generated
   */
  Declaration createDeclaration();

  /**
   * Returns a new object of class '<em>Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Definition</em>'.
   * @generated
   */
  Definition createDefinition();

  /**
   * Returns a new object of class '<em>With</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>With</em>'.
   * @generated
   */
  With createWith();

  /**
   * Returns a new object of class '<em>Option</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Option</em>'.
   * @generated
   */
  Option createOption();

  /**
   * Returns a new object of class '<em>Ref Device</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ref Device</em>'.
   * @generated
   */
  RefDevice createRefDevice();

  /**
   * Returns a new object of class '<em>Attribut</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribut</em>'.
   * @generated
   */
  Attribut createAttribut();

  /**
   * Returns a new object of class '<em>Led Impl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Led Impl</em>'.
   * @generated
   */
  Led_Impl createLed_Impl();

  /**
   * Returns a new object of class '<em>Led Blink</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Led Blink</em>'.
   * @generated
   */
  LedBlink createLedBlink();

  /**
   * Returns a new object of class '<em>Camera</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Camera</em>'.
   * @generated
   */
  Camera createCamera();

  /**
   * Returns a new object of class '<em>Type Generic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Generic</em>'.
   * @generated
   */
  TypeGeneric createTypeGeneric();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DrnPackage getDrnPackage();

} //DrnFactory
