/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flip</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sar.drone.drn.DrnPackage#getFlip()
 * @model
 * @generated
 */
public interface Flip extends DepXYZ_IMPL
{
} // Flip
