/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial Direction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sar.drone.drn.InitialDirection#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see sar.drone.drn.DrnPackage#getInitialDirection()
 * @model
 * @generated
 */
public interface InitialDirection extends InitialPosition
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link sar.drone.drn.DirectionType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see sar.drone.drn.DirectionType
   * @see #setValue(DirectionType)
   * @see sar.drone.drn.DrnPackage#getInitialDirection_Value()
   * @model
   * @generated
   */
  DirectionType getValue();

  /**
   * Sets the value of the '{@link sar.drone.drn.InitialDirection#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see sar.drone.drn.DirectionType
   * @see #getValue()
   * @generated
   */
  void setValue(DirectionType value);

} // InitialDirection
