/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Part Lib</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sar.drone.drn.RefPartLib#getLib <em>Lib</em>}</li>
 *   <li>{@link sar.drone.drn.RefPartLib#getAssignement <em>Assignement</em>}</li>
 * </ul>
 *
 * @see sar.drone.drn.DrnPackage#getRefPartLib()
 * @model
 * @generated
 */
public interface RefPartLib extends Movement
{
  /**
   * Returns the value of the '<em><b>Lib</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lib</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lib</em>' reference.
   * @see #setLib(Library)
   * @see sar.drone.drn.DrnPackage#getRefPartLib_Lib()
   * @model
   * @generated
   */
  Library getLib();

  /**
   * Sets the value of the '{@link sar.drone.drn.RefPartLib#getLib <em>Lib</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lib</em>' reference.
   * @see #getLib()
   * @generated
   */
  void setLib(Library value);

  /**
   * Returns the value of the '<em><b>Assignement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignement</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignement</em>' reference.
   * @see #setAssignement(Assignement)
   * @see sar.drone.drn.DrnPackage#getRefPartLib_Assignement()
   * @model
   * @generated
   */
  Assignement getAssignement();

  /**
   * Sets the value of the '{@link sar.drone.drn.RefPartLib#getAssignement <em>Assignement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignement</em>' reference.
   * @see #getAssignement()
   * @generated
   */
  void setAssignement(Assignement value);

} // RefPartLib
