/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sar.drone.drn.Rotate#getName <em>Name</em>}</li>
 *   <li>{@link sar.drone.drn.Rotate#getAngleCST <em>Angle CST</em>}</li>
 *   <li>{@link sar.drone.drn.Rotate#getAngleVAR <em>Angle VAR</em>}</li>
 *   <li>{@link sar.drone.drn.Rotate#getTempsCST <em>Temps CST</em>}</li>
 *   <li>{@link sar.drone.drn.Rotate#getTempsVAR <em>Temps VAR</em>}</li>
 * </ul>
 *
 * @see sar.drone.drn.DrnPackage#getRotate()
 * @model
 * @generated
 */
public interface Rotate extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see sar.drone.drn.DrnPackage#getRotate_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link sar.drone.drn.Rotate#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Angle CST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Angle CST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle CST</em>' attribute.
   * @see #setAngleCST(String)
   * @see sar.drone.drn.DrnPackage#getRotate_AngleCST()
   * @model
   * @generated
   */
  String getAngleCST();

  /**
   * Sets the value of the '{@link sar.drone.drn.Rotate#getAngleCST <em>Angle CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Angle CST</em>' attribute.
   * @see #getAngleCST()
   * @generated
   */
  void setAngleCST(String value);

  /**
   * Returns the value of the '<em><b>Angle VAR</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Angle VAR</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle VAR</em>' reference.
   * @see #setAngleVAR(Parametre)
   * @see sar.drone.drn.DrnPackage#getRotate_AngleVAR()
   * @model
   * @generated
   */
  Parametre getAngleVAR();

  /**
   * Sets the value of the '{@link sar.drone.drn.Rotate#getAngleVAR <em>Angle VAR</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Angle VAR</em>' reference.
   * @see #getAngleVAR()
   * @generated
   */
  void setAngleVAR(Parametre value);

  /**
   * Returns the value of the '<em><b>Temps CST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temps CST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps CST</em>' attribute.
   * @see #setTempsCST(String)
   * @see sar.drone.drn.DrnPackage#getRotate_TempsCST()
   * @model
   * @generated
   */
  String getTempsCST();

  /**
   * Sets the value of the '{@link sar.drone.drn.Rotate#getTempsCST <em>Temps CST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temps CST</em>' attribute.
   * @see #getTempsCST()
   * @generated
   */
  void setTempsCST(String value);

  /**
   * Returns the value of the '<em><b>Temps VAR</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temps VAR</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps VAR</em>' reference.
   * @see #setTempsVAR(Parametre)
   * @see sar.drone.drn.DrnPackage#getRotate_TempsVAR()
   * @model
   * @generated
   */
  Parametre getTempsVAR();

  /**
   * Sets the value of the '{@link sar.drone.drn.Rotate#getTempsVAR <em>Temps VAR</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temps VAR</em>' reference.
   * @see #getTempsVAR()
   * @generated
   */
  void setTempsVAR(Parametre value);

} // Rotate
