/**
 * generated by Xtext 2.10.0
 */
package sar.drone.drn.impl;

import org.eclipse.emf.ecore.EClass;

import sar.drone.drn.DrnPackage;
import sar.drone.drn.Vmax;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vmax</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VmaxImpl extends LimitImpl implements Vmax
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VmaxImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DrnPackage.Literals.VMAX;
  }

} //VmaxImpl
