/*
 * generated by Xtext 2.10.0
 */
package sar.drone.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import sar.drone.drn.And;
import sar.drone.drn.Assignement;
import sar.drone.drn.BACKWARD;
import sar.drone.drn.CARREXY;
import sar.drone.drn.CARREYZ;
import sar.drone.drn.CERCLEXY;
import sar.drone.drn.CERCLEYZ;
import sar.drone.drn.CameraBottom;
import sar.drone.drn.CameraFront;
import sar.drone.drn.Context;
import sar.drone.drn.DOWN;
import sar.drone.drn.DepXY;
import sar.drone.drn.DepXYZ;
import sar.drone.drn.DepXZ;
import sar.drone.drn.DepYZ;
import sar.drone.drn.DrnPackage;
import sar.drone.drn.FORWARD;
import sar.drone.drn.Flip;
import sar.drone.drn.Hmax;
import sar.drone.drn.LEFT;
import sar.drone.drn.Land;
import sar.drone.drn.LedBlink;
import sar.drone.drn.Led_Impl;
import sar.drone.drn.Model;
import sar.drone.drn.Parametre;
import sar.drone.drn.RIGHT;
import sar.drone.drn.RefPart;
import sar.drone.drn.Rotate;
import sar.drone.drn.TakeOff;
import sar.drone.drn.UP;
import sar.drone.drn.Vmax;
import sar.drone.drn.Wait;
import sar.drone.drn.With;
import sar.drone.services.DrnGrammarAccess;

@SuppressWarnings("all")
public class DrnSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DrnGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DrnPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DrnPackage.AND:
				if (rule == grammarAccess.getAndRule()) {
					sequence_And(context, (And) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_And_Expression(context, (And) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.ASSIGNEMENT:
				sequence_Assignement(context, (Assignement) semanticObject); 
				return; 
			case DrnPackage.BACKWARD:
				if (rule == grammarAccess.getDepY_ImplRule()
						|| rule == grammarAccess.getBACKWARDRule()) {
					sequence_BACKWARD(context, (BACKWARD) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_BACKWARD_Expression(context, (BACKWARD) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.CARREXY:
				if (rule == grammarAccess.getDepXY_IMPLRule()
						|| rule == grammarAccess.getCARREXYRule()) {
					sequence_CARREXY(context, (CARREXY) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_CARREXY_Expression(context, (CARREXY) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.CARREYZ:
				if (rule == grammarAccess.getDepYZ_IMPLRule()
						|| rule == grammarAccess.getCARREYZRule()) {
					sequence_CARREYZ(context, (CARREYZ) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_CARREYZ_Expression(context, (CARREYZ) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.CERCLEXY:
				if (rule == grammarAccess.getDepXY_IMPLRule()
						|| rule == grammarAccess.getCERCLEXYRule()) {
					sequence_CERCLEXY(context, (CERCLEXY) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_CERCLEXY_Expression(context, (CERCLEXY) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.CERCLEYZ:
				if (rule == grammarAccess.getDepYZ_IMPLRule()
						|| rule == grammarAccess.getCERCLEYZRule()) {
					sequence_CERCLEYZ(context, (CERCLEYZ) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_CERCLEYZ_Expression(context, (CERCLEYZ) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.CAMERA_BOTTOM:
				sequence_CameraBottom(context, (CameraBottom) semanticObject); 
				return; 
			case DrnPackage.CAMERA_FRONT:
				sequence_CameraFront(context, (CameraFront) semanticObject); 
				return; 
			case DrnPackage.CONTEXT:
				sequence_Context(context, (Context) semanticObject); 
				return; 
			case DrnPackage.DOWN:
				if (rule == grammarAccess.getDepZ_ImplRule()
						|| rule == grammarAccess.getDOWNRule()) {
					sequence_DOWN(context, (DOWN) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_DOWN_Expression(context, (DOWN) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.DEP_XY:
				if (rule == grammarAccess.getDepXY_IMPLRule()
						|| rule == grammarAccess.getDepXYRule()) {
					sequence_DepXY(context, (DepXY) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_DepXY_Expression(context, (DepXY) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.DEP_XYZ:
				if (rule == grammarAccess.getDepXYZ_IMPLRule()
						|| rule == grammarAccess.getDepXYZRule()) {
					sequence_DepXYZ(context, (DepXYZ) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_DepXYZ_Expression(context, (DepXYZ) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.DEP_XZ:
				if (rule == grammarAccess.getDepXZ_IMPLRule()
						|| rule == grammarAccess.getDepXZRule()) {
					sequence_DepXZ(context, (DepXZ) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_DepXZ_Expression(context, (DepXZ) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.DEP_YZ:
				if (rule == grammarAccess.getDepYZ_IMPLRule()
						|| rule == grammarAccess.getDepYZRule()) {
					sequence_DepYZ(context, (DepYZ) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getExpressionRule()) {
					sequence_DepYZ_Expression(context, (DepYZ) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.FORWARD:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_FORWARD(context, (FORWARD) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getDepY_ImplRule()
						|| rule == grammarAccess.getFORWARDRule()) {
					sequence_FORWARD(context, (FORWARD) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.FLIP:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_Flip(context, (Flip) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getDepXYZ_IMPLRule()
						|| rule == grammarAccess.getFlipRule()) {
					sequence_Flip(context, (Flip) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.HMAX:
				sequence_Hmax(context, (Hmax) semanticObject); 
				return; 
			case DrnPackage.LEFT:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_LEFT(context, (LEFT) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getDepX_ImplRule()
						|| rule == grammarAccess.getLEFTRule()) {
					sequence_LEFT(context, (LEFT) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.LAND:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_Land(context, (Land) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLandRule()) {
					sequence_Land(context, (Land) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.LED_BLINK:
				sequence_LedBlink(context, (LedBlink) semanticObject); 
				return; 
			case DrnPackage.LED_IMPL:
				sequence_Led_Impl(context, (Led_Impl) semanticObject); 
				return; 
			case DrnPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case DrnPackage.PARAMETRE:
				sequence_Parametre(context, (Parametre) semanticObject); 
				return; 
			case DrnPackage.RIGHT:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_RIGHT(context, (RIGHT) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getDepX_ImplRule()
						|| rule == grammarAccess.getRIGHTRule()) {
					sequence_RIGHT(context, (RIGHT) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.REF_PART:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_RefPart(context, (RefPart) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getRefPartRule()) {
					sequence_RefPart(context, (RefPart) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.ROTATE:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_Rotate(context, (Rotate) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getRotateRule()) {
					sequence_Rotate(context, (Rotate) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.TAKE_OFF:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_TakeOff(context, (TakeOff) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getTakeOffRule()) {
					sequence_TakeOff(context, (TakeOff) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.UP:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_UP(context, (UP) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getDepZ_ImplRule()
						|| rule == grammarAccess.getUPRule()) {
					sequence_UP(context, (UP) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.VMAX:
				sequence_Vmax(context, (Vmax) semanticObject); 
				return; 
			case DrnPackage.WAIT:
				if (rule == grammarAccess.getExpressionRule()) {
					sequence_Expression_Wait(context, (Wait) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getWaitRule()) {
					sequence_Wait(context, (Wait) semanticObject); 
					return; 
				}
				else break;
			case DrnPackage.WITH:
				sequence_With(context, (With) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     And returns And
	 *
	 * Constraint:
	 *     (
	 *         name='merge' 
	 *         (
	 *             rotate+=Rotate | 
	 *             depx+=DepX_Impl | 
	 *             depy+=DepY_Impl | 
	 *             depxz+=DepXZ_IMPL | 
	 *             depxy+=DepXY_IMPL | 
	 *             depz+=DepZ_Impl
	 *         ) 
	 *         (
	 *             rotate+=Rotate | 
	 *             depx+=DepX_Impl | 
	 *             depy+=DepY_Impl | 
	 *             depxz+=DepXZ_IMPL | 
	 *             depxy+=DepXY_IMPL | 
	 *             depz+=DepZ_Impl
	 *         ) 
	 *         (
	 *             rotate+=Rotate | 
	 *             depx+=DepX_Impl | 
	 *             depy+=DepY_Impl | 
	 *             depxz+=DepXZ_IMPL | 
	 *             depxy+=DepXY_IMPL | 
	 *             depz+=DepZ_Impl
	 *         )*
	 *     )
	 */
	protected void sequence_And(ISerializationContext context, And semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns And
	 *
	 * Constraint:
	 *     (
	 *         name='merge' 
	 *         (
	 *             rotate+=Rotate | 
	 *             depx+=DepX_Impl | 
	 *             depy+=DepY_Impl | 
	 *             depxz+=DepXZ_IMPL | 
	 *             depxy+=DepXY_IMPL | 
	 *             depz+=DepZ_Impl
	 *         ) 
	 *         (
	 *             rotate+=Rotate | 
	 *             depx+=DepX_Impl | 
	 *             depy+=DepY_Impl | 
	 *             depxz+=DepXZ_IMPL | 
	 *             depxy+=DepXY_IMPL | 
	 *             depz+=DepZ_Impl
	 *         ) 
	 *         rotate+=Rotate? 
	 *         ((depx+=DepX_Impl | depy+=DepY_Impl | depxz+=DepXZ_IMPL | depxy+=DepXY_IMPL | depz+=DepZ_Impl)? rotate+=Rotate?)* 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_And_Expression(ISerializationContext context, And semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Assignement returns Assignement
	 *
	 * Constraint:
	 *     (name=ID (parametre+=Parametre parametre+=Parametre*)? operandes+=Expression operandes+=Expression*)
	 */
	protected void sequence_Assignement(ISerializationContext context, Assignement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepY_Impl returns BACKWARD
	 *     BACKWARD returns BACKWARD
	 *
	 * Constraint:
	 *     (name='backward' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_BACKWARD(ISerializationContext context, BACKWARD semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns BACKWARD
	 *
	 * Constraint:
	 *     (
	 *         name='backward' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_BACKWARD_Expression(ISerializationContext context, BACKWARD semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepXY_IMPL returns CARREXY
	 *     CARREXY returns CARREXY
	 *
	 * Constraint:
	 *     (name='carreXY' (coteCST=EInt | coteVAR=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_CARREXY(ISerializationContext context, CARREXY semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns CARREXY
	 *
	 * Constraint:
	 *     (
	 *         name='carreXY' 
	 *         (coteCST=EInt | coteVAR=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_CARREXY_Expression(ISerializationContext context, CARREXY semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepYZ_IMPL returns CARREYZ
	 *     CARREYZ returns CARREYZ
	 *
	 * Constraint:
	 *     (name='carreYZ' (coteCST=EInt | coteVAR=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_CARREYZ(ISerializationContext context, CARREYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns CARREYZ
	 *
	 * Constraint:
	 *     (
	 *         name='carreYZ' 
	 *         (coteCST=EInt | coteVAR=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_CARREYZ_Expression(ISerializationContext context, CARREYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepXY_IMPL returns CERCLEXY
	 *     CERCLEXY returns CERCLEXY
	 *
	 * Constraint:
	 *     (name='cercleXY' (rayonCST=EInt | rayonVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_CERCLEXY(ISerializationContext context, CERCLEXY semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns CERCLEXY
	 *
	 * Constraint:
	 *     (
	 *         name='cercleXY' 
	 *         (rayonCST=EInt | rayonVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_CERCLEXY_Expression(ISerializationContext context, CERCLEXY semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepYZ_IMPL returns CERCLEYZ
	 *     CERCLEYZ returns CERCLEYZ
	 *
	 * Constraint:
	 *     (name='cercleYZ' (rayonCST=EInt | rayonVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_CERCLEYZ(ISerializationContext context, CERCLEYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns CERCLEYZ
	 *
	 * Constraint:
	 *     (
	 *         name='cercleYZ' 
	 *         (rayonCST=EInt | rayonVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_CERCLEYZ_Expression(ISerializationContext context, CERCLEYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Option returns CameraBottom
	 *     CameraBottom returns CameraBottom
	 *
	 * Constraint:
	 *     (name='cameraBottom' mode=Mode)
	 */
	protected void sequence_CameraBottom(ISerializationContext context, CameraBottom semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.OPTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.OPTION__NAME));
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.CAMERA_BOTTOM__MODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.CAMERA_BOTTOM__MODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCameraBottomAccess().getNameCameraBottomKeyword_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getCameraBottomAccess().getModeModeEnumRuleCall_3_0(), semanticObject.getMode());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Option returns CameraFront
	 *     CameraFront returns CameraFront
	 *
	 * Constraint:
	 *     (name='cameraFront' mode=Mode)
	 */
	protected void sequence_CameraFront(ISerializationContext context, CameraFront semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.OPTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.OPTION__NAME));
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.CAMERA_FRONT__MODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.CAMERA_FRONT__MODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCameraFrontAccess().getNameCameraFrontKeyword_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getCameraFrontAccess().getModeModeEnumRuleCall_3_0(), semanticObject.getMode());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Context returns Context
	 *
	 * Constraint:
	 *     (limit+=Limit limit+=Limit*)
	 */
	protected void sequence_Context(ISerializationContext context, Context semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepZ_Impl returns DOWN
	 *     DOWN returns DOWN
	 *
	 * Constraint:
	 *     (name='down' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_DOWN(ISerializationContext context, DOWN semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns DOWN
	 *
	 * Constraint:
	 *     (
	 *         name='down' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_DOWN_Expression(ISerializationContext context, DOWN semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepXYZ_IMPL returns DepXYZ
	 *     DepXYZ returns DepXYZ
	 *
	 * Constraint:
	 *     (name='depXYZ' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_DepXYZ(ISerializationContext context, DepXYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns DepXYZ
	 *
	 * Constraint:
	 *     (
	 *         name='depXYZ' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_DepXYZ_Expression(ISerializationContext context, DepXYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepXY_IMPL returns DepXY
	 *     DepXY returns DepXY
	 *
	 * Constraint:
	 *     (name='depXY' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_DepXY(ISerializationContext context, DepXY semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns DepXY
	 *
	 * Constraint:
	 *     (
	 *         name='depXY' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_DepXY_Expression(ISerializationContext context, DepXY semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepXZ_IMPL returns DepXZ
	 *     DepXZ returns DepXZ
	 *
	 * Constraint:
	 *     (name='depXZ' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_DepXZ(ISerializationContext context, DepXZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns DepXZ
	 *
	 * Constraint:
	 *     (
	 *         name='depXZ' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_DepXZ_Expression(ISerializationContext context, DepXZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepYZ_IMPL returns DepYZ
	 *     DepYZ returns DepYZ
	 *
	 * Constraint:
	 *     (name='depYZ' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_DepYZ(ISerializationContext context, DepYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns DepYZ
	 *
	 * Constraint:
	 *     (
	 *         name='depYZ' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_DepYZ_Expression(ISerializationContext context, DepYZ semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns FORWARD
	 *
	 * Constraint:
	 *     (
	 *         name='forward' 
	 *         (distanceVar=[Parametre|ID] | distanceCST=EInt) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_FORWARD(ISerializationContext context, FORWARD semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns Flip
	 *
	 * Constraint:
	 *     (
	 *         name='flip' 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_Flip(ISerializationContext context, Flip semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns LEFT
	 *
	 * Constraint:
	 *     (
	 *         name='left' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_LEFT(ISerializationContext context, LEFT semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns Land
	 *
	 * Constraint:
	 *     (
	 *         name='land' 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_Land(ISerializationContext context, Land semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns RIGHT
	 *
	 * Constraint:
	 *     (
	 *         name='right' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_RIGHT(ISerializationContext context, RIGHT semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns RefPart
	 *
	 * Constraint:
	 *     (
	 *         variable_partie=[Assignement|ID] 
	 *         params+=EInt* 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_RefPart(ISerializationContext context, RefPart semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns Rotate
	 *
	 * Constraint:
	 *     (
	 *         name='rotate' 
	 *         (angleCST=EInt | angleVAR=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_Rotate(ISerializationContext context, Rotate semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns TakeOff
	 *
	 * Constraint:
	 *     (
	 *         name='takeoff' 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_TakeOff(ISerializationContext context, TakeOff semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns UP
	 *
	 * Constraint:
	 *     (
	 *         name='up' 
	 *         (distanceCST=EInt | distanceVar=[Parametre|ID]) 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_UP(ISerializationContext context, UP semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns Wait
	 *
	 * Constraint:
	 *     (
	 *         name='wait' 
	 *         (tempsCST=EInt | tempsVAR=[Parametre|ID]) 
	 *         (
	 *             ((repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?) | 
	 *             (then+=Expression then+=Expression* (repeatCST=EInt | repeatVAR=[Parametre|ID])? with+=With?)
	 *         )
	 *     )
	 */
	protected void sequence_Expression_Wait(ISerializationContext context, Wait semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepY_Impl returns FORWARD
	 *     FORWARD returns FORWARD
	 *
	 * Constraint:
	 *     (name='forward' (distanceVar=[Parametre|ID] | distanceCST=EInt) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_FORWARD(ISerializationContext context, FORWARD semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DepXYZ_IMPL returns Flip
	 *     Flip returns Flip
	 *
	 * Constraint:
	 *     name='flip'
	 */
	protected void sequence_Flip(ISerializationContext context, Flip semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.DEP_XYZ_IMPL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.DEP_XYZ_IMPL__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFlipAccess().getNameFlipKeyword_0_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Limit returns Hmax
	 *     Hmax returns Hmax
	 *
	 * Constraint:
	 *     (name='hmax' value=EInt)
	 */
	protected void sequence_Hmax(ISerializationContext context, Hmax semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.LIMIT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.LIMIT__NAME));
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.LIMIT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.LIMIT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHmaxAccess().getNameHmaxKeyword_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getHmaxAccess().getValueEIntParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DepX_Impl returns LEFT
	 *     LEFT returns LEFT
	 *
	 * Constraint:
	 *     (name='left' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_LEFT(ISerializationContext context, LEFT semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Land returns Land
	 *
	 * Constraint:
	 *     name='land'
	 */
	protected void sequence_Land(ISerializationContext context, Land semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.LAND__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.LAND__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLandAccess().getNameLandKeyword_0_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Option returns LedBlink
	 *     LedBlink returns LedBlink
	 *
	 * Constraint:
	 *     (name='ledBlink' color=ColorLed (blink_per_secCST=EInt | blink_per_secVAR=[Parametre|ID]))
	 */
	protected void sequence_LedBlink(ISerializationContext context, LedBlink semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Option returns Led_Impl
	 *     Led_Impl returns Led_Impl
	 *
	 * Constraint:
	 *     (name='led' color=ColorLed)
	 */
	protected void sequence_Led_Impl(ISerializationContext context, Led_Impl semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.OPTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.OPTION__NAME));
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.LED_IMPL__COLOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.LED_IMPL__COLOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLed_ImplAccess().getNameLedKeyword_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getLed_ImplAccess().getColorColorLedEnumRuleCall_4_0(), semanticObject.getColor());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (context=Context? assignement+=Assignement assignement+=Assignement* main=RefPart)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Parametre returns Parametre
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Parametre(ISerializationContext context, Parametre semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.PARAMETRE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.PARAMETRE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParametreAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DepX_Impl returns RIGHT
	 *     RIGHT returns RIGHT
	 *
	 * Constraint:
	 *     (name='right' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_RIGHT(ISerializationContext context, RIGHT semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     RefPart returns RefPart
	 *
	 * Constraint:
	 *     (variable_partie=[Assignement|ID] params+=EInt*)
	 */
	protected void sequence_RefPart(ISerializationContext context, RefPart semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Rotate returns Rotate
	 *
	 * Constraint:
	 *     (name='rotate' (angleCST=EInt | angleVAR=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_Rotate(ISerializationContext context, Rotate semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     TakeOff returns TakeOff
	 *
	 * Constraint:
	 *     name='takeoff'
	 */
	protected void sequence_TakeOff(ISerializationContext context, TakeOff semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.TAKE_OFF__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.TAKE_OFF__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTakeOffAccess().getNameTakeoffKeyword_0_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     DepZ_Impl returns UP
	 *     UP returns UP
	 *
	 * Constraint:
	 *     (name='up' (distanceCST=EInt | distanceVar=[Parametre|ID]) (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_UP(ISerializationContext context, UP semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Limit returns Vmax
	 *     Vmax returns Vmax
	 *
	 * Constraint:
	 *     (name='vmax' value=EInt)
	 */
	protected void sequence_Vmax(ISerializationContext context, Vmax semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.LIMIT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.LIMIT__NAME));
			if (transientValues.isValueTransient(semanticObject, DrnPackage.Literals.LIMIT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DrnPackage.Literals.LIMIT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVmaxAccess().getNameVmaxKeyword_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getVmaxAccess().getValueEIntParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Wait returns Wait
	 *
	 * Constraint:
	 *     (name='wait' (tempsCST=EInt | tempsVAR=[Parametre|ID]))
	 */
	protected void sequence_Wait(ISerializationContext context, Wait semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     With returns With
	 *
	 * Constraint:
	 *     (name='with' option+=Option option+=Option*)
	 */
	protected void sequence_With(ISerializationContext context, With semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
